### ISSUE TITLE
Missing Home Instance Node

### ISSUE THREAD

**Issue by Sounomi** [gw2-api/issues#3]
### Current Behavior

The **Prismaticite Node** is missing from API data.

### Expected Behavior

The **Prismaticite Node** should be included in the proper API endpoints.

### Steps To Reproduce

1. Visit https://api.guildwars2.com/v2/home/nodes
2. The Prismaticite Node has not yet been added.

### Happening since

17 November 2020‎ (Build 108,580)

### Anything else?

Unlocked by https://api.guildwars2.com/v2/items?ids=94286&lang=en

**Comment by qtip** [comment]
Should be good. See you the next this issue reopens :)
See: https://api.guildwars2.com/v2/home/nodes

**Comment by darthmaim** [comment]
Confirmed to be working now :)
