### ISSUE TITLE
/v2/achievements from EoD and SotO have region "Unknown"

### ISSUE THREAD

**Issue by gitglint** [gw2-api/issues#30]
### Current Behavior

All achievements from/in End-of-Dragons have "Unknown" as the region name in API call /v2/achievements.

### Expected Behavior

The region should be "Cantha" or something similar that stands for End-of-Dragon region

### Steps To Reproduce

Example:

https://api.guildwars2.com/v2/achievements?ids=6127&lang=en

```
[
  {
    "id": 6127,
    "name": "Shock-Wave Jumper",
    "description": "",
    "requirement": "Jump over 10 shock waves from Soo-Won's tail slam.",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 10,
        "points": 1
      }
    ],
    "rewards": [
      {
        "type": "Mastery",
        "region": "Unknown",
        "id": 661
      }
    ]
  }
]
```

### Happening since

Release of End of Dragons

**Comment by darthmaim** [comment]
Same of SotO masteries

**Comment by darthmaim** [comment]
This is now in the API
