### ISSUE TITLE
/v2/masteries does not show the new mastery tracks from End of Dragons

### ISSUE THREAD

**Issue by gitglint** [gw2-api/issues#31]
### Current Behavior

The API call shows only ids 1-27, but not any of the new mastery tracks from End-of-Dragons.

### Expected Behavior

Show ids > 27

### Steps To Reproduce

Example: https://api.guildwars2.com/v2/masteries

[
  1,
  2,
  3,
  4,
  5,
  6,
  8,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27
]

### Happening since

Release of End of Dragons

**Comment by darthmaim** [comment]
This is now in the API
