### ISSUE TITLE
/v2/account/masteries   All masteries from End-of-Dragons are missing

### ISSUE THREAD

**Issue by gitglint** [gw2-api/issues#32]
### Current Behavior

Highest mastery id in API response is 27

### Expected Behavior

ids > 27

### Steps To Reproduce

Example: https://api.guildwars2.com/v2/account/masteries?access_token=<deleted>

[
  {
    "id": 1,
    "level": 4
  },
  {
    "id": 2,
    "level": 5
  },
  {
    "id": 3,
    "level": 5
  },
  {
    "id": 4,
    "level": 4
  },
  {
    "id": 5,
    "level": 3
  },
  {
    "id": 6,
    "level": 3
  },
  {
    "id": 8,
    "level": 5
  },
  {
    "id": 12,
    "level": 3
  },
  {
    "id": 13,
    "level": 5
  },
  {
    "id": 14,
    "level": 3
  },
  {
    "id": 15,
    "level": 4
  },
  {
    "id": 16,
    "level": 2
  },
  {
    "id": 17,
    "level": 3
  },
  {
    "id": 18,
    "level": 3
  },
  {
    "id": 19,
    "level": 3
  },
  {
    "id": 20,
    "level": 2
  },
  {
    "id": 21,
    "level": 2
  },
  {
    "id": 22,
    "level": 3
  },
  {
    "id": 23,
    "level": 3
  },
  {
    "id": 24,
    "level": 3
  },
  {
    "id": 25,
    "level": 3
  },
  {
    "id": 26,
    "level": 5
  },
  {
    "id": 27,
    "level": 6
  }
]

### Happening since

Release of End of Dragons

### Anything else?

The account I tested this with has purchased EoD and has several EoD masteries maxed.

**Comment by Archomeda** [comment]
Related to #31

**Comment by darthmaim** [comment]
This is now in the API
