### ISSUE TITLE
/v2/recipes incorrect content-type header

### ISSUE THREAD

**Issue by immortius** [gw2-api/issues#33]
### Current Behavior

Currently the /v2/recipes api returns 
content-type: application/json; utf-8

### Expected Behavior

It should return
content-type: application/json; charset=utf-8

### Steps To Reproduce

1. Open browser developer console
2. Browse to https://api.guildwars2.com/v2/recipes
3. Observe response content-type header

### Happening since

9 March 2022ish

### Anything else?

Not much of an issue in the browser, but some programmatic clients fail to handle this (in my case Java's rs-api/jersey)

**Comment by Feenposhleen** [comment]
This problem has spread to the `/achievements/*` endpoints as well. It breaks my current project using Darts default `http` package.

**Comment by immortius** [comment]
Looks like this is fixed now.
