### ISSUE TITLE
/v2/items has placeholder item types

### ISSUE THREAD

**Issue by jcmoyer** [gw2-api/issues#34]
### Current Behavior

Some items have a type of "Qux" or "Quux" since EoD's release.

### Expected Behavior

These items should have a proper type name.

### Steps To Reproduce

https://api.guildwars2.com/v2/items?ids=95582,95800,95801,95802,95864,95904,95923,95948,96070,96299,96360,96450,96467,96474,96477,96590,96613,96618,96628,96654,96826,96853,96871,96919,96992,97020,97041,97101,97107,97284,97289,97339,97410,97535,97553,97572,97656,97686,97775

### Happening since

Since the API was re-enabled after EoD

**Comment by greaka** [comment]
An additional example of a gathering tool of type "Foo"
https://api.guildwars2.com/v2/items/95993

**Comment by queicherius** [comment]
Fixed since latest patch.
