### ISSUE TITLE
`/v2/mapchests`: Hero's Choice Chests added after EoD missing

### ISSUE THREAD

**Issue by Doreiko** [gw2-api/issues#37]
### Current Behavior

The API endpoints for /mapchests are missing the End of Dragons Hero's Choice Chests. These are used for tracking daily completion.

```json
[
  "auric_basin_heros_choice_chest",
  "crystal_oasis_heros_choice_chest",
  "domain_of_vabbi_heros_choice_chest",
  "dragons_stand_heros_choice_chest",
  "elon_riverlands_heros_choice_chest",
  "tangled_depths_heros_choice_chest",
  "the_desolation_heros_choice_chest",
  "verdant_brink_heros_choice_chest"
]
```

### Expected Behavior

```diff
[
  "auric_basin_heros_choice_chest",
  "crystal_oasis_heros_choice_chest",
  "domain_of_vabbi_heros_choice_chest",
+ "dragons_end_heros_choice_chest",
  "dragons_stand_heros_choice_chest",
+ "echovald_wilds_heros_choice_chest",
  "elon_riverlands_heros_choice_chest",
+ "new_kaineng_city_heros_choice_chest",
+ "seitung_province_heros_choice_chest",
  "tangled_depths_heros_choice_chest",
  "the_desolation_heros_choice_chest",
  "verdant_brink_heros_choice_chest"
]
```

### Steps To Reproduce

https://api.guildwars2.com/v2/account/mapchests?access_token=[APIkey]
https://api.guildwars2.com/v2/mapchests

### Happening since

03/17/2022 when they were added.

**Comment by TheMrMilchmann** [comment]
Unfortunately this is still an issue and the new SotO chests are also not exposed:

- https://wiki.guildwars2.com/wiki/Amnytas:_Hero%27s_Choice_Chest
- https://wiki.guildwars2.com/wiki/Skywatch_Archipelago:_Hero%27s_Choice_Chest

**Comment by Stonos** [comment]
Not sure if this is helpful, but here is a list of all Hero's Choice Chests that are currently missing, along with the event that awards them:

| Hero's Choice Chest  | Event that awards it                                |
|----------------------|-----------------------------------------------------|
| [Seitung Province](https://wiki.guildwars2.com/wiki/Seitung_Province:_Hero%27s_Choice_Chest)     | [Defeat Renyak!](https://wiki.guildwars2.com/wiki/Defeat_Renyak!)                                      |
| [New Kaineng City](https://wiki.guildwars2.com/wiki/New_Kaineng_City:_Hero%27s_Choice_Chest)     | [Destroy the corruption before the system overloads!](https://wiki.guildwars2.com/wiki/Destroy_the_corruption_before_the_system_overloads!) |
| [Echovald Wilds](https://wiki.guildwars2.com/wiki/Echovald_Wilds:_Hero%27s_Choice_Chest)       | [Defeat Prototype XJ-1](https://wiki.guildwars2.com/wiki/Defeat_Prototype_XJ-1)                               |
| [Dragon's End](https://wiki.guildwars2.com/wiki/Dragon%27s_End:_Hero%27s_Choice_Chest)         | [Defeat Soo-Won](https://wiki.guildwars2.com/wiki/Defeat_Soo-Won)                                      |
| [Gyala Delve](https://wiki.guildwars2.com/wiki/Gyala_Delve:_Hero%27s_Choice_Chest)          | [Defeat the ravenous wanderer](https://wiki.guildwars2.com/wiki/Destroy_the_ravenous_wanderer)                        |
| [Skywatch Archipelago](https://wiki.guildwars2.com/wiki/Skywatch_Archipelago:_Hero%27s_Choice_Chest) | [Purge Lyhr's corruption](https://wiki.guildwars2.com/wiki/Purge_Lyhr's_corruption)                             |
| [Amnytas](https://wiki.guildwars2.com/wiki/Amnytas:_Hero%27s_Choice_Chest)              | [Defeat Nourys, the Eyes of the Abyss](https://wiki.guildwars2.com/wiki/Defeat_Nourys,_the_Eyes_of_the_Abyss)                |
| [Inner Nayos](https://wiki.guildwars2.com/wiki/Inner_Nayos:_Hero%27s_Choice_Chest)          | [Defeat Ignaxious](https://wiki.guildwars2.com/wiki/Defeat_Ignaxious)<br>[Defeat Knaebelag the Terror](https://wiki.guildwars2.com/wiki/Defeat_Knaebelag_the_Terror)                                  |
| [Convergence](https://wiki.guildwars2.com/wiki/Convergence:_Hero%27s_Choice_Chest)          | [Convergences](https://wiki.guildwars2.com/wiki/Convergences)                                        |
| [Citadel of Zakiros](https://wiki.guildwars2.com/wiki/Citadel_of_Zakiros:_Hero%27s_Choice_Chest)   | [Defeat Eparch, the Consumed King](https://wiki.guildwars2.com/wiki/Defeat_Eparch,_the_Consumed_King)                    |

**Comment by darthmaim** [comment]
Theses seem to be all included now, even the new Janthir Wilds chest is there 😮
