### ISSUE TITLE
Jade Bot and Fishing for /characters

### ISSUE THREAD

**Issue by thoanny** [gw2-api/issues#39]
### Feature Description

ATM there is no way to know wich items equipped on characters for:

* Jade Bot
    * Core
    * Sensory Array
    * Service Chip
* Fishing :
    * Fishing Rod
    * Bait
    * Lure

### Implementation

The easiest way for us: adding jade bot and fishing equipments in /characters/:name/equipment, using `id` (item_id), `slot` (JadeBotCore, JadebotModule1, JadebotModule1, FishingRod, FishingBait, FishingLure) and `charges` for FishingBait, FishingLure.

Maybe the easy way for you: adding new endpoints: `/characters/:name/fishing` and `/characters/:name:/jadebot`

**Comment by darthmaim** [comment]
This was added to the API some time ago, see https://github.com/gw2efficiency/issues/issues/1611#issuecomment-1739863308
