### ISSUE TITLE
Missing PvP Seasons

### ISSUE THREAD

**Issue by Sounomi** [gw2-api/issues#4]
### Current Behavior

The following PvP seasons are missing on the API:

- PvP League Season Twenty-Five (January 5, 2021 - March 1, 2021)
- PvP League 3v3 Season Two (October 13, 2020 - October 26, 2020)

### Expected Behavior

The two seasons should be included in the API data.

### Steps To Reproduce

1. Visit https://api.guildwars2.com/v2/pvp/seasons?ids=all
2. The PvP seasons aren't included in the data while seasons after them are.

### Happening since

October 13, 2020

**Comment by dsnider-anet** [comment]
Submitted

**Comment by darthmaim** [comment]
This is confirmed working now: https://api.guildwars2.com/v2/pvp/seasons?ids=FC69E01A-EF08-446D-AA87-91E007E5813E,C17559C2-DC5E-4FDD-9558-F333A7A65352
