### ISSUE TITLE
/v2/items is missing items for existing itemIds

### ISSUE THREAD

**Issue by Taschenbuch** [gw2-api/issues#41]
### Current Behavior

you can find item ids for these items ingame in inventories etc (e.g. /v2/characters), but you cannot resolve them via /v2/items. 

- missing items: 
itemIds behind the link. 
You can click on the "Api" link on the wiki page instead as well
https://wiki.guildwars2.com/wiki/Black_Lion_Mining_Pick 20326
https://wiki.guildwars2.com/wiki/Black_Lion_Harvesting_Sickle 20324
https://wiki.guildwars2.com/wiki/Black_Lion_Logging_Axe 20325
https://wiki.guildwars2.com/wiki/Master_Mining_Pick 23034,23022,23028
https://wiki.guildwars2.com/wiki/Master_Logging_Axe 23033,23021,23027
https://wiki.guildwars2.com/wiki/Master_Harvesting_Sickle 23032,23020,23026 

### Expected Behavior

- should return item details.
- example for item that returns correct response:
https://wiki.guildwars2.com/wiki/Copper_Mining_Pick -> https://api.guildwars2.com/v2/items?ids=23031&lang=en

### Steps To Reproduce

1. send api request: https://api.guildwars2.com/v2/items?ids=20326&lang=en for https://wiki.guildwars2.com/wiki/Black_Lion_Mining_Pick
2. api returns: "all ids provided are invalid"

### Happening since

2022-05-02

### Anything else?

from other repo, maybe related:
https://github.com/arenanet/api-cdi/issues/680

**Comment by Zdesl** [comment]
same behavior with
https://wiki.guildwars2.com/wiki/Chest_of_the_Echovald_Wilds_Hero 97693

**Comment by darthmaim** [comment]
All those items were once available in the API, but got removed again. I'm closing this issue in favor of the more general #89
