### ISSUE TITLE
Missing quests for End of Dragon stories

### ISSUE THREAD

**Issue by queicherius** [gw2-api/issues#44]
### Current Behavior

The API does correctly return the stories for End of Dragons (e.g. [Convergence](https://api.guildwars2.com/v2/stories/112)), but it does not report any quests for these stories. This also means that `/v2/characters/:id/quests` can not be used to read out the completion status.

### Expected Behavior

The API should return the quests for End of Dragon stories.

### Steps To Reproduce

1. Open https://api.guildwars2.com/v2/quests?ids=all&v=latest
2. Search for `quest.story === 112` (or any other EoD story id or matching in-game name)
3. Observe that there are no matches

### Happening since

Release of End of Dragons

**Comment by Tometheus** [comment]
Just adding that it now does not include post-EoD content either.  (Living World S1 redux, etc)

**Comment by darthmaim** [comment]
This is now in the API
