### ISSUE TITLE
Discrepancy between ids: /v2/commerce/prices & /v2/items/{id}

### ISSUE THREAD

**Issue by M-Smits** [gw2-api/issues#55]
### Current Behavior

When executing a call to /v2/commerce/prices , a list with item ids is returned from API.
When executing a separate call for each id in said list to /v2/items/{id} some of the ids are not found.

### Expected Behavior

When executing a call to /v2/commerce/prices , a list with item ids is returned from API.
When executing a separate call for each id in said list to /v2/items/{id} all of the ids are found.

### Steps To Reproduce

List of ids that I can find in /v2/commerce/prices **but not in /v2/items/{id}**: [36401, 36666, 21651, 20216, 43983, 43984, 43986, 43987, 43988, 43999, 14907, 14913, 14915, 14918, 37306, 37312, 37321, 37343, 37374, 37379, 37427, 37445, 37464, 37492, 37505, 37513, 37525, 37531, 37534, 37558, 37608, 9590", 37648, 37685, 37704, 37708, 37711, 37727, 37732, 37756 ]

1. First I checked that the missing id's are actually in -> https://api.guildwars2.com/v2/commerce/prices
2. Then I checked it by making call to (example) -> https://api.guildwars2.com/v2/items/37704
3. Pick any of the id's in the list. You will find them in prices. But you cannot find details by /v2/items/{id}

### Anything else?

![Screenshot 2023-04-08 at 18 52 41](https://user-images.githubusercontent.com/9571065/230733374-019c7b4f-4bba-43aa-8023-dd6f71a3ef0a.png)
![Screenshot 2023-04-08 at 18 53 32](https://user-images.githubusercontent.com/9571065/230733414-9df9a041-8f79-4624-bff6-563204acaf98.png)

**Comment by darthmaim** [comment]
Yeah, that is kind of expected, because there are quite a few items on the TP that don't exist in the game anymore. All items have to be whitelisted (which for example happens when a player gets the item). There are quite a few other endpoints that also contain items that are not whitelisted.

Btw, you can request multiple items at once like this: https://api.guildwars2.com/v2/items?ids=36401,36666,21651,20216,43983,43984,43986,43987,43988,43999,14907,14913,14915,14918,37306,37312,37321,37343,37374,37379,37427,37445,37464,37492,37505,37513,37525,37531,37534,37558,37608,9590%22,37648,37685,37704,37708,37711,37727,37732,37756

**Comment by M-Smits** [comment]
> Yeah, that is kind of expected, because there are quite a few items on the TP that don't exist in the game anymore. All items have to be whitelisted (which for example happens when a player gets the item). There are quite a few other endpoints that also contain items that are not whitelisted.
> 
> Btw, you can request multiple items at once like this: https://api.guildwars2.com/v2/items?ids=36401,36666,21651,20216,43983,43984,43986,43987,43988,43999,14907,14913,14915,14918,37306,37312,37321,37343,37374,37379,37427,37445,37464,37492,37505,37513,37525,37531,37534,37558,37608,9590%22,37648,37685,37704,37708,37711,37727,37732,37756

Thank you for the help. I am confused with the definition of whitelisting?

https://wiki.guildwars2.com/wiki/API:2/commerce/prices:
- "whitelisted (boolean) – Indicates whether or not **a free to play account** can purchase or sell this item on the trading" post. It notes nothing of the item being removed from the game?

**Comment by darthmaim** [comment]
- The property "whitelisted" indicates if F2P players can trade this item on the TP.
- There is an additional whitelist in the API that controls which items get returned by the API.
