### ISSUE TITLE
/v2/characters/:id/skills returns 404 when requesting with version (v) parameter

### ISSUE THREAD

**Issue by its-felix** [gw2-api/issues#62]
### Current Behavior

When requesting `/v2/characters/:id/skills` with a version (v) parameter like so:
```
https://api.guildwars2.com/v2/characters/Lisa%20Lilwani/skills?v=latest
```

The response is always 404:
```
Status: 404

Headers:
content-length: 27
content-type: application/json; charset=utf-8

Body:
{
  "reason": "not found"
}
```

### Expected Behavior

The endpoint should allow to request a specific version.

### Steps To Reproduce

1. Request `https://api.guildwars2.com/v2/characters/:id/skills?v=latest` using an accesstoken and a character of the account

### Happening since

Not sure - noticed 2023-08-28 (post SotO)

**Comment by TheMrMilchmann** [comment]
This is expected. The endpoint was removed as of `2019-12-19T00:00:00.000Z` and replaced with `/v2/characters/:id/buildtabs` ([GW2 Wiki](https://wiki.guildwars2.com/wiki/API:2/characters/:id/buildtabs)).
