### ISSUE TITLE
`/v2/account` does not show `SecretsOfTheObscure` in the `access` array

### ISSUE THREAD

**Issue by queicherius** [gw2-api/issues#66]
### Current Behavior

`/v2/account` does not show `SecretsOfTheObscure` in the `access` array

### Expected Behavior

`/v2/account` should contain `SecretsOfTheObscure` in the `access` array

### Steps To Reproduce

1. Open `/v2/account?v=latest&access_token=<...>` for an account that has Secrets of the Obscure unlocked
2. Observe the missing entry in the access array

### Happening since

Release of SotO (I assume)

**Comment by queicherius** [comment]
In 72 days it would also be nice to have `JanthirWilds` added to it 🙂

**Comment by queicherius** [comment]
On top of this bug, the array also sometimes lists the flat out wrong expansions. I'm looking at a friend's account that has all expansions unlocked, but the API reports `["GuildWars2", "PlayForFree", "PathOfFire", "EndOfDragons"]` (not a f2p account and missing Heart of Thorns)

**Comment by darthmaim** [comment]
`"SecretsOfTheObscure"` and `"JanthirWilds"` are now included
