### ISSUE TITLE
`/v2/achievements`: The "Dragonstorm" achievement category is missing achievements

### ISSUE THREAD

**Issue by queicherius** [gw2-api/issues#68]
### Current Behavior

The Dragonstorm category shows most achievements, but the achievements Light Him Up, Put Them on Ice and Steelcaught are missing. Their original, previous IDs are also no longer resolving.

### Expected Behavior

The achievements are not missing.

### Steps To Reproduce

1. Open https://api.guildwars2.com/v2/achievements?ids=5695,5702,5689
2. Observe the achievements are missing

### Happening since

N/A

### Anything else?

Related #54

**Comment by queicherius** [comment]
Also [The Path of Most Resistance](https://api.guildwars2.com/v2/achievements?ids=6534) and [Gaze into the Void](https://api.guildwars2.com/v2/achievements?ids=6526)

**Comment by darthmaim** [comment]
Since all 5 achievements listed in the issue were once in the API. I'm closing this in favor of

- #89

**Comment by awesumness** [comment]
These are fixed https://api.guildwars2.com/v2/achievements?ids=5695,5702,5689
