### ISSUE TITLE
Missing Story Quests

### ISSUE THREAD

**Issue by Sounomi** [gw2-api/issues#7]
### Current Behavior

The story quests for Season 5, Episode 5 "Champions" is missing under /v2/quests.

### Expected Behavior

The story quests should be available.

### Steps To Reproduce

1. Go to https://api.guildwars2.com/v2/quests?ids=all
2. Look for any quests belonging to story ID "98"

### Happening since

2020/11/17

### Anything else?

Story has an entry on the API: https://api.guildwars2.com/v2/stories?id=98
Wiki page: https://wiki.guildwars2.com/wiki/Champions

Was mentioned on Discord briefly but never really pushed as a bug that needs fixing.

**Comment by dsnider-anet** [comment]
I believe this was fixed with the recent static content update

**Comment by darthmaim** [comment]
looks good!
