### ISSUE TITLE
`/v2/guild/:id/log`: 504 Gateway Time-out

### ISSUE THREAD

**Issue by msniveau** [gw2-api/issues#90]
### Current Behavior

Fetching the log of a guild using the `/v2/guild/:id/log` endpoint currently results in a timeout.

This also applies when the ?since parameter is set to the most recent log entry it was able to fetch, so probably not a missing-pagination-issue. Also tried with 6 different guilds and two different accounts with the same result, so its not related to the account used to authenticate or guild the log is fetched for.

### Expected Behavior

The Endpoint should respond with the list of log entries.

### Happening since

May 22nd

### Anything else?

This issue is mentioned on the [Guild Wars 2 Developer Discord](https://discord.com/channels/384735285197537290/384735523521953792/1252395129315266674) few times already. Its probably related with the 6th guild slot.

Created the bug report even if its already a known issue to have something to reference to when ppl ask me why the bot does not work (and to keep track myself)

**Comment by darthmaim** [comment]
This seems to be working again.
