### ISSUE TITLE
`/v2/commerce/listings`: Nougat Center (36061) listings returns 502 on API, inaccessible in-game

### ISSUE THREAD

**Issue by jcmoyer** [gw2-api/issues#94]
### Current Behavior

Accessing `/v2/commerce/listings/36061` or including item ID 36061 in a multi-listing query such as `/v2/commerce/listings?ids=19709,36061` causes the whole query to fail with a 502 bad gateway.

### Expected Behavior

The request should succeed.

### Steps To Reproduce

1. Navigate to [/v2/commerce/listings/36061](https://api.guildwars2.com/v2/commerce/listings/36061)
2. Wait a bit and observe 502

### Happening since

2024-08-23

### Anything else?

I haven't been able to make this request since the API was re-enabled after Janthir Wilds released. Other listings seem to work fine.

**Comment by darthmaim** [comment]
This is probably because there are currently 42.789.114 listings for this item, and the API server times out generating the response.

**Comment by jcmoyer** [comment]
This is now happening with [Chattering Skull (36060)](https://api.guildwars2.com/v2/commerce/listings?ids=36060) and will probably happen with the other halloween item.
